### ISSUE TITLE
Replace state/country columns with region/country_id

### ISSUE THREAD

**Issue by ynicolaou** [RJMetrics/magenerator#13]
This fields are on the `sales_flat_order_address` table.
`region`'s data type should stay the same, `VARCHAR(255)`
`country_id`'s data type should be `VARCHAR(2)`, where the data it stores is a 2 letter abreviation of the country, such as `GB` or `CA`.

**Comment by bengarvey** [comment]
@ynicolaou Do you have examples of region id's?

**Comment by bengarvey** [comment]
http://creatingawebstore.com/magento-states-code-list-for-table-rates-shipping.html

**Comment by bengarvey** [comment]
First pass at this, I'm not going to worry about regions being in the right country

**Comment by bengarvey** [comment]
https://github.com/RJMetrics/magenerator/pull/18
