### ISSUE TITLE
Add base_discount_amount to sales_flat_order

### ISSUE THREAD

**Issue by alexkleger** [RJMetrics/magenerator#14]
`base_discount_amount` should be a DECIMAL(12,4), default to 0.0000.

Discounts are represented as negative values in Magento. There should be a decent distribution of orders with and without discounts. Ideally if `coupon_code` is not null, `base_discount_amount` will also not be 0.0000. Additionally the `base_discount_amount` should be less than `base_grand_total`.

**Comment by robertjmoore** [comment]
will be addressed as part of branch realistic_repeats

**Comment by robertjmoore** [comment]
resolved in realistic_repeats, merge pending
