### ISSUE TITLE
Alter customer data to have more realistic repeat behaviors

### ISSUE THREAD

**Issue by eogilvy** [RJMetrics/magenerator#24]
A good example is Lia Sophia, Internal Team account, Buying behavior and retention dashboard, Repeat order probability report

This has about 75% with one purchase and decrease to ~15% for 2 purchases, ~5% for 3 purchases

https://admin.rjmetrics.com/admin/v3b/user/45066
https://dashboard.rjmetrics.com/v2/client/7032/dashapp/419833 (uses incremental event probability as opposed to the new way we build it in the report builder but the data will display the same)
https://dashboard.rjmetrics.com/v2/client/7032/dashapp/419833

**Comment by robertjmoore** [comment]
figured this out and pushed up code into realistic_repeats branch; merge pending code review
