### ISSUE TITLE
Fake Google Ecommerce integration on the sales_flat_order table

### ISSUE THREAD

**Issue by alexkleger** [RJMetrics/magenerator#25]
For websites that have Google's ecommerce tracking setup, this allows you to attribute events (cart checkout, hitting a subscribe button), with UTM tags.  To demonstrate the end-goal of this integration, please add the following fields to the `sales_flat_order_table`:

- utm_source
- utm_medium
- utm_campaign

Source - the source of the traffic. This could be a random distribution of:

- Google
- Facebook
- Twitter
- Newsletter
- (direct)

Medium - the medium the link was clicked:

- organic
- (none)
- referral
- email
- cpc
- socialmedia

Campaign - the name of the campaign or promotion. This is a little more open ended:

- (not set)
- 15% Campaign
- Welcome20
- Retargeting
- Cyber Monday
- Launch Sale
- Half off Tuesdays

(campaign values should eventually map to a fake AdWords source table as well to enable ROI)

**Comment by robertjmoore** [comment]
resolved in realistic_repeats branch, merge pending
