### ISSUE TITLE
Differentiating `sales_flat_order.status`

### ISSUE THREAD

**Issue by eogilvy** [RJMetrics/magenerator#30]
Right now, all 3000 orders are in a `complete` sales_flat_order.status.  Is there any way we can differentiate these?  

Below is an example of EZkosher's spread:

status	count
complete	 20097
processing 3657
pending	307
canceled	32
picked	21
shipped	19
picking	14
pending_paypal	1
out_for_delivery	1
delivered	1

**Comment by robertjmoore** [comment]
addressed in realistic_repeats branch, merge pending
