### ISSUE TITLE
Make `product_type` function as expected

### ISSUE THREAD

**Issue by alexkleger** [RJMetrics/magenerator#32]
Product_type on `sales_flat_order_item` currently returns "tools". This function in Magento as the identifier of the product type, not category. Which means it should return "simple", "configurable", "bundle", "downloadable", "grouped" or "virtual", outlined here: http://docs.magento.com/m1/ce/user_guide/catalog/product-types.html.

In an ideal world each product on `sfoi` would have two lines, one for the "simple" and one for the "configurable".

Related to: https://github.com/RJMetrics/magenerator/issues/15

**Comment by bengarvey** [comment]
https://github.com/RJMetrics/magenerator/pull/48
