### ISSUE TITLE
Create `core_store` table and accompanying foreign keys

### ISSUE THREAD

**Issue by alexkleger** [RJMetrics/magenerator#39]
This table serves as a mapping table for store name / store website. The names are front-facing friendly. Schema:

```
   store_id (smallint(5) unsigned) 
   code (varchar(32))
   group_id (smallint(5) unsigned)
   is_active (smallint(5) unsigned)
   name (varchar(255))
   sort_order (smallint(5) unsigned)
   website_id (smallint(5) unsigned)
```

store_id serves a key for `store_id` on sales_flat_order and customer_entity
code is a shortened version of name
website / group_id are optional, idk what they do
name is the store's name
sort_order / is_active are NOT necessary

note the 'core_store' is 'store' in M2

**Comment by alexkleger** [comment]
`store_id` should be available on the following tables:

- customer_entity
- sales_flat_order
- sales_flat_order_item

**Comment by bengarvey** [comment]
@alexkleger This is complete, right?

**Comment by alexkleger** [comment]
@bengarvey yes. 🏖
